### ISSUE TITLE
Zephyr SDK 0.8.2 newlib headers no longer provide gettimeofday() prototype by default

### ISSUE THREAD

**Issue by zephyrbot** [zephyrproject-rtos/meta-zephyr-sdk#63]
**_Reported by Paul Sokolovsky:_**

Building JerryScript Zephyr port with 0.8.2 SDK, I get following error:

```
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/jerryscript/targets/default/jerry-port-default-date.c:34:7: error: implicit declaration of function 'gettimeofday' [-Werror=implicit-function-declaration]
   if (gettimeofday (&tv, &tz) != 0)
```

This code built fine with SDK 0.8.1. The error above appears to happen for any arch (arm and x86 for sure).

Looking at zephyr-sdk-0.8.2/sysroots/armv5-poky-eabi/usr/include/sys/time.h:

{code:c}
#if __MISC_VISIBLE || __XSI_VISIBLE
int _EXFUN(getitimer, (int __which, struct itimerval *__value));
int _EXFUN(setitimer, (int __which, const struct itimerval *__restrict __value,
					struct itimerval *__restrict __ovalue));
int _EXFUN(gettimeofday, (struct timeval *__restrict __p,
			  void *__restrict __tz));
#endif
{code}

So, apparently __MISC_VISIBLE or __XSI_VISIBLE not (no longer) defined to 1. I was able to work that around by compiling with -D_XOPEN_SOURCE, which in turn defines __XSI_VISIBLE.

But http://pubs.opengroup.org/onlinepubs/7908799/xsh/systime.h.html doesn't specify any special requirements for gettimeofday() to be visible, just "The following [including gettimeofday] are declared as functions and may also be defined as macros. Function prototypes must be provided for use with an ISO C compiler."

Btw, I guess this is regression after upgrading newlib to 2.4.0 (or whatever version, I'm writing by memory).

(Imported from Jira SDK-44)
